networks:
  monitoring2:
    driver: bridge
services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins_edasuda  # Change from 'jenkins' to 'jenkins_edasuda'
    user: root
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace:ro  # Mount project root as read-only to /workspace
      - ./Jenkinsfile:/var/jenkins_home/workspace/Projects_edasuda-pipeline/Jenkinsfile
      #- ./:/var/jenkins_home/workspace/Projects/edasuda-pipeline:rw
      - ./jenkins/init.groovy.d:/var/jenkins_home/init.groovy.d
      - ./jenkins/casc_configs:/var/jenkins_home/casc_configs
    ports:
      - "8082:8080"
      - "50000:50000"
    environment:
      - JENKINS_ADMIN_USER=admin
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD:-adminpass}
      - REPOSITORY_URL=${REPOSITORY_URL:-https://github.com/maxwebgt/edasuda.git}
      - GITHUB_USERNAME=${GITHUB_USERNAME:-maxwebgt}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - AUTO_DEPLOY=true
      - MONGO_URI_PASSWORD=${MONGO_URI_PASSWORD:-example}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MONGO_URI=mongodb://root:${MONGO_URI_PASSWORD:-example}@mongo:27017/admin
      - JENKINS_UC_INSECURE=true
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/
    command: >
      bash -c "
        mkdir -p /var/jenkins_home/workspace/Projects &&
        chmod -R 777 /var/jenkins_home/workspace &&
        mkdir -p /var/jenkins_home/init.groovy.d &&
        echo '
          import jenkins.model.*
          import hudson.security.*
          def jenkins = Jenkins.getInstance()
          def strategy = new hudson.security.AuthorizationStrategy.Unsecured()
          jenkins.setAuthorizationStrategy(strategy)
          def realm = new HudsonPrivateSecurityRealm(false)
          jenkins.setSecurityRealm(realm)
          jenkins.save()
          println \"Security has been disabled\"
        ' > /var/jenkins_home/init.groovy.d/disable-security.groovy &&
        chmod 644 /var/jenkins_home/init.groovy.d/*.groovy &&
        /usr/local/bin/jenkins.sh"
    networks:
      - monitoring2
    restart: unless-stopped
    labels:
      logging: "promtail"
      com.docker.compose.service: "jenkins"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
volumes:
  jenkins_home:
    driver: local