version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api_app
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo

  tg_bot:
    build:
      context: ./tg_bot
      dockerfile: Dockerfile
    container_name: tg_bot_app
    environment:
      - TELEGRAM_BOT_TOKEN=7637457882:AAHbeS-f8bNRdN0GKSLwjM1K2NBXFjBpc9g
    ports:
      - "5001:5001"
    volumes:
      - ./tg_bot:/app
      - /app/node_modules  # Это позволит сохранить установленные зависимости
    depends_on:
      - mongo
      - api

volumes:
  mongo_data:
    driver: local