networks:
  monitoring2:
    driver: bridge
services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins_edasuda  # Change from 'jenkins' to 'jenkins_edasuda'
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace:rw
      - ./Jenkinsfile:/var/jenkins_home/workspace/Projects_edasuda-pipeline/Jenkinsfile
      - ./jenkins/init.groovy.d:/var/jenkins_home/init.groovy.d
    ports:
      - "8082:8080"
      - "50000:50000"
    environment:
      - JENKINS_ADMIN_USER=admin
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD:-adminpass}
      - REPOSITORY_URL=${REPOSITORY_URL:-https://github.com/maxwebgt/edasuda.git}
      - GITHUB_USERNAME=${GITHUB_USERNAME:-maxwebgt}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - AUTO_DEPLOY=true
      - MONGO_URI_PASSWORD=${MONGO_URI_PASSWORD:-example}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MONGO_URI=mongodb://root:${MONGO_URI_PASSWORD:-example}@mongo:27017/admin
      - JENKINS_UC_INSECURE=true
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    command: >
      bash -c "
        # Create workspace directory and fix permissions
        mkdir -p /var/jenkins_home/workspace/Projects;
        chmod -R 777 /var/jenkins_home/workspace;
        
        # Ensure the required init.groovy.d directory exists
        mkdir -p /var/jenkins_home/init.groovy.d;
        
        # Create or update the disable-security.groovy script
        cat > /var/jenkins_home/init.groovy.d/disable-security.groovy << 'EOL'
        import jenkins.model.*
        import hudson.security.*

        // Get Jenkins instance
        def jenkins = Jenkins.getInstance()

        // Disable security
        def strategy = new hudson.security.AuthorizationStrategy.Unsecured()
        jenkins.setAuthorizationStrategy(strategy)

        def realm = new HudsonPrivateSecurityRealm(false)
        jenkins.setSecurityRealm(realm)

        // Save configuration
        jenkins.save()

        println \"Security has been disabled\"
        EOL
        
        # Copy scripts from mounted volume if they exist
        cp -f /workspace/jenkins/init.groovy.d/*.groovy /var/jenkins_home/init.groovy.d/ 2>/dev/null || true;
        
        # Verify Docker Compose installation
        if ! command -v docker-compose &> /dev/null; then
          echo 'Docker Compose not found, installing directly...';
          curl -SL \"https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)\" -o /usr/local/bin/docker-compose;
          chmod +x /usr/local/bin/docker-compose;
          echo 'Docker Compose installed successfully:';
          docker-compose --version;
        else
          echo 'Docker Compose is available at:';
          which docker-compose;
          docker-compose --version;
        fi
        
        # Set proper permissions for groovy scripts
        chmod 644 /var/jenkins_home/init.groovy.d/*.groovy 2>/dev/null || true;
        
        # Start Jenkins
        exec /usr/local/bin/jenkins.sh
      "
    networks:
      - monitoring2
    restart: unless-stopped
    labels:
      logging: "promtail"
      com.docker.compose.service: "jenkins"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
volumes:
  jenkins_home:
    driver: local