apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    uid: prometheus

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    isDefault: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: "trace_id"
          matcherRegex: "traceID=(\\w+)"
          url: "$${__value.raw}"
