{
 "title": "MongoDB Dashboard",
 "refresh": "5s",
 "panels": [
  {
   "title": "MongoDB Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"mongodb\",instance=\"mongodb_exporter:9216\"}",
     "legendFormat": "MongoDB Status"
    }
   ]
  },
  {
   "title": "MongoDB Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "mongodb_connections{instance=\"mongodb_exporter:9216\"}",
     "legendFormat": "{{state}} connections"
    }
   ]
  },
  {
   "title": "MongoDB Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mongodb_memory{instance=\"mongodb_exporter:9216\"}",
     "legendFormat": "Memory {{type}}"
    }
   ]
  }
 ]
}