jobs:
  - script: >
      pipelineJob('auto-deploy-edasuda') {
        description('Автоматически созданное задание для развертывания проекта edasuda')
        
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/maxwebgt/edasuda.git')
                  credentials('github-credentials')
                }
                branch('*/main')
                extensions {
                  cleanBeforeCheckout()
                  cloneOptions {
                    shallow(true)
                    timeout(5)
                  }
                }
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
        
        triggers {
          githubPush()
          scm('H/5 * * * *')
        }
        
        properties {
          disableConcurrentBuilds()
          githubProjectUrl('https://github.com/maxwebgt/edasuda.git')
        }
      }
