server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          environment: test
          user: maxwebgt
          __path__: /var/log/*.log

  # Добавьте конфигурацию для тестового лога
  - job_name: test
    static_configs:
      - targets:
          - localhost
        labels:
          job: testlogs
          environment: test
          user: maxwebgt
          __path__: /var/log/mongod.log