server:
  http_listen_port: 9080
  grpc_listen_port: 9097

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'

  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/*.log

  - job_name: mongodb_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: mongodb
          __path__: /var/log/mongodb/*.log
          
  # Add Jenkins logs scraping
  - job_name: jenkins_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: jenkins
          __path__: /var/jenkins_home/logs/*.log
    pipeline_stages:
      - match:
          selector: '{job="jenkins"}'
          stages:
            - regex:
                expression: '(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3})\+\d{4} (?P<level>[A-Z]+) (?P<message>.*)'
            - labels:
                level: