server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs: attrs
    relabel_configs:
      - source_labels: ['__path__']
        target_label: container_name
        regex: '/var/lib/docker/containers/([^/]+).*'
        replacement: '$1'

  - job_name: pm2_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: pm2
          __path__: /var/log/pm2/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            message: msg
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          level: